package com.sdr.sdr;

import com.mongodb.BasicDBList;
import com.mongodb.BasicDBObject;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;
import static com.sdr.sdr.Main.db;

/**
 *
 * @author Heladio
 */
public class AgregarFlexible extends javax.swing.JFrame {
    
    private static final String REGEX_LINE = "^.+[\n$]";
    private static final String REGEX_KEY = "^\\w+:";
    //private static final String REGEX_VALUE = ":\w+\\s*$";
    
    public static Pattern LinePattern = Pattern.compile(REGEX_LINE);
    public static Pattern KeyPattern = Pattern.compile(REGEX_KEY);
    //public static Pattern ValuePattern = Pattern.compile(REGEX_VALUE);
    public Matcher matcher;
    private Map<String, List<String>> datos;

    public AgregarFlexible() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtArticulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtInformacion = new javax.swing.JTextArea();
        BtnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Artículo:");

        jLabel2.setText("Información:");

        TxtInformacion.setColumns(20);
        TxtInformacion.setRows(5);
        jScrollPane1.setViewportView(TxtInformacion);

        BtnAceptar.setText("Aceptar");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addComponent(TxtArticulo)))
                    .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166)
                .addComponent(BtnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        if (!valido()) {
            return;
        }
        String[] keyValue;
        List<String> values;
        datos = new HashMap<>();
        //Agregar Datos comunes
        values = new ArrayList<>(1);
        values.add(TxtArticulo.getText().trim().toUpperCase());
        datos.put("ARTICULO", values);
        //Agregar Datos de información
        for (String line: TxtInformacion.getText().split("\\R")) {
            if (!line.contains(":")) {
                JOptionPane.showMessageDialog(null, "Información redactada incorrectamente\n"
                        + "Asegúrese de separar las características de su valor\n"
                        + "Ejemplo 1 - característica : valor\n"
                        + "Ejemplo 2 - característica : valor, valor, valor, ...", "Atención",
                        JOptionPane.WARNING_MESSAGE);
                break;
            }
            keyValue = line.split(":");
            values = new ArrayList<>();
            if (keyValue[1].contains(",")) {
                for(String value: keyValue[1].split(",")) {
                    if (!value.trim().isEmpty()) {
                        values.add(value.trim().toUpperCase());
                    }
                }
            } else if (!keyValue[1].trim().isEmpty()) {
                values.add(keyValue[1].trim().toUpperCase());
            }
            datos.put(keyValue[0].trim().toUpperCase(), values);
        }
        agregar(datos);
    }//GEN-LAST:event_BtnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JTextField TxtArticulo;
    private javax.swing.JTextArea TxtInformacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void agregar(Map<String, List<String>> datos) {
        BasicDBObject documento = new BasicDBObject();
        datos.forEach((key, values) -> {
            if (values.size() == 1) {
                documento.put(key, values.get(0));
            } else {
                BasicDBList lista = new BasicDBList();
                lista.addAll(values);
                documento.put(key, lista);
            }
        });
        db.getCollection("productos").insert(documento);
    }

    private boolean valido() {
        return true;
    }
}
